In [2]:
import numpy as np

- numpy ist eine Library, die es ermöglicht, einfacher mit Zahlen zu rechnen
- Arbeitsspeicher schonender

In [3]:
# Zahlen in einem Array können direkt multipliziert werden 
list = np.array([1,2,3,4])
print(list * 2)

[2 4 6 8]


In [4]:
# ohne numpy passiert folgendes
normalList = [1,2,3,4]
print(normalList * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


### Matrix

In [5]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


#### Stelle in Matrix addressieren

In [6]:
print(matrix[0,0])
print(matrix[1,2])

1
6


#### Spalte in Matrix addressieren

In [7]:
# gib mir aus allen Zeilen (:) die erste Spalte
print(matrix[:,0])

[1 4]


In [8]:
# gib mir aus der zweiten Zeile alle Einträge
print(matrix[1,:])

[4 5 6]


#### Arrays

In [9]:
normalArray = [1,2,3]
print(normalArray)

numpyArray = np.array([1,2,3])
print(numpyArray)

[1, 2, 3]
[1 2 3]


shape: Listet die Anzahl der Einträge in einem Array auf 

In [10]:
names = np.array(["Anton", "Susi", "Hank"])
print(names)
names.shape

['Anton' 'Susi' 'Hank']


(3,)

In [11]:
entries = np.array([[1,2,3], [4,5,6]])
print(entries)
print("shapes:")
print(entries.shape)
print("first entry:")
print(entries[0])

[[1 2 3]
 [4 5 6]]
shapes:
(2, 3)
first entry:
[1 2 3]


reshape: Umarrangieren von Werten in einem Array

In [16]:
entries = np.array([[[1.1, 1.2],[2.1, 2.2],[3.1, 3.2]]])
print(entries)
print("shapes:")
print(entries.shape)
print("first entry:")

# reshape: erlaubt z.B. das Umstrukturieren eines Arrays
# z.B. mache aus dem Array (1,3,2) ein Array, in dem die hinteren Einträge gemerged werden
print("reshaped:")
print(entries.reshape(1, 6))
# oder mache aus dem Array (1,3,2) ein Array, in dem die Einträge auf zwei Zeilen mit je drei Einträgen verteilt werden
print(entries.reshape(2, 3))

# np kann auch selbst ausrechnen, wieviele Einträge in einem Array sind. Daher kann auch die Schreibweise "-1" gewählt werden
print("selbst ausgerechnet:")
print(entries.reshape(-1, 3))

[[[1.1 1.2]
  [2.1 2.2]
  [3.1 3.2]]]
shapes:
(1, 3, 2)
first entry:
reshaped:
[[1.1 1.2 2.1 2.2 3.1 3.2]]
[[1.1 1.2 2.1]
 [2.2 3.1 3.2]]
and?
[[1.1 1.2 2.1]
 [2.2 3.1 3.2]]


In [13]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])